apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: {{ .Values.sonarr.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.sonarr.service.port }}
      protocol: TCP
      targetPort: 8989
  selector:
    app: sonarr
  type: ClusterIP
