apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
spec:
  replicas: {{ .Values.sonarr.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        release: sonarr
    spec:
      initContainers:
      - name: copy
        image: busybox:1.28
        env:
          - name: PUID
            value: {{ quote .Values.PUID }}
          - name: PGID
            value: {{ quote .Values.PGID }}
        command: ["/bin/sh", "-c"]
        args: 
          - ls /tmp/config/;
            cp /tmp/config/*.xml /config/;
            cp /tmp/config/*.sh /init-scripts/;
            cp /tmp/config/*.json /init-scripts/;
            chmod 744 /init-scripts/init.sh;
            chown -R ${PUID}:${PGID} /tv;
        volumeMounts:
          - mountPath: /config/
            name: sonarr-config
          - mountPath: /init-scripts/
            name: sonarr-init
          - mountPath: /tmp/config
            name: sonarr-configmap
          - mountPath: /tv
            name: data
            subPath: {{ .Values.library.tv }}
      containers:
        - image: 'linuxserver/sonarr:latest'
          imagePullPolicy: IfNotPresent
          name: sonarr
          env:
            - name: PUID
              value: {{ quote .Values.PUID }}
            - name: PGID
              value: {{ quote .Values.PGID }}
          ports:
            - containerPort: 8989
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            {{ if eq .Values.sonarr.persistDirectory true }}
            - mountPath: /config
              name: data
              subPath: {{ .Values.sonarr.configPath }}
            {{ end }}
            - mountPath: /downloads/transmission
              name: data
              subPath: {{ .Values.transmission.dataPath }}
            - mountPath: /tv
              name: data
              subPath: {{ .Values.library.tv }}
            - mountPath: /config/config.xml
              name: sonarr-config
              subPath: config.xml
            - mountPath: /init-scripts/
              name: sonarr-init
            - mountPath: /custom-cont-init.d/custom-init.sh
              name: sonarr-init
              subPath: custom-init.sh
      nodeSelector:
        storage: "true"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
        - configMap:
            name: sonarr-configmap
          name: sonarr-configmap
        - name: sonarr-config
        - name: sonarr-init
