apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        release: radarr
    spec:
      containers:
        - image: 'linuxserver/radarr:latest'
          imagePullPolicy: IfNotPresent
          name: radarr
          env:
            - name: PUID
              value: {{ quote .Values.PUID }}
            - name: PGID
              value: {{ quote .Values.PGID }}
          securityContext:
            runAsUser: {{ .Values.PUID }}
            runAsGroup: {{ .Values.PGID }}
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /downloads/transmission
              name: transmission
              subPath: radarr
            - mountPath: /movies
              name: media
              subPath: movies
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-server-nfs-pvc
        - name: transmission
          persistentVolumeClaim:
            claimName: transmission-downloaded-pvc
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc