apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: {{ .Values.radarr.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.radarr.service.port }}
      protocol: TCP
      targetPort: 7878
  selector:
    app: radarr
  type: ClusterIP
