apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-configmap
data:
  config.xml: |-
    <Config>
      <UrlBase>{{ .Values.radarr.contextPath }}</UrlBase>
      <ApiKey>{{ .Values.radarr.apiKey }}</ApiKey>
    </Config>
  custom-init.sh: |-
    #!/bin/bash
    echo "running init script in background"
    /init-scripts/init.sh &
  init.sh: |-
    #!/bin/bash

    while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -X 'GET' 'http://localhost:7878{{ .Values.radarr.contextPath }}/api/v3/health' -H 'X-Api-Key: {{ .Values.radarr.apiKey }}')" != "200" ]]; 
    do 
      echo "waiting for API to return 200"
      sleep 5; 
    done

    echo "call all init curls"
    for f in /init-scripts/*.json; 
    do 
        z=(${f//./ })
        contextPath=${z[1]}
        echo "calling $contextPath for $f"
        curl -k -X 'POST' \
            "http://localhost:7878{{ .Values.radarr.contextPath }}/api/v3/$contextPath" \
            -H 'accept: application/json' \
            -H "X-Api-Key: {{ .Values.radarr.apiKey }}" \
            -H 'Content-Type: application/json' \
            --data @$f
    done
  1.rootfolder.json: |-
    {
      "path": "/movies",
      "accessible": true
    }
  2.downloadclient.json: |-
    {
      "enable": true,
      "protocol": "torrent",
      "removeCompletedDownloads": true,
      "removeFailedDownloads": true,
      "name": "transmission",
      "fields": [
        {
          "name": "host",
          "value": "{{ .Values.transmission.service.name }}"
        },
        {
          "name": "port",
          "value": {{ .Values.transmission.service.port }}
        },
        {
          "name": "urlBase",
          "value": "{{ .Values.transmission.contextPath }}"
        }
      ],
      "implementation": "Transmission",
      "configContract": "TransmissionSettings"
    }
