{{ if .Values.plex.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex
spec:
  ports:
    - name: pms
      port: 32400
      protocol: TCP
      targetPort: pms
  selector:
    app: plex
  type: ClusterIP
{{ end }}