apiVersion: v1
kind: Service
metadata:
  labels:
    app: overseerr
  name: {{ .Values.overseerr.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.overseerr.service.port }}
      protocol: TCP
      targetPort: 5055
  selector:
    app: overseerr
  type: ClusterIP
