apiVersion: v1
kind: ConfigMap
metadata:
  name: bazarr-configmap
data:
  config.ini: |-
    [general]
    ip = 0.0.0.0
    port = 6767
    base_url = {{ .Values.bazarr.contextPath }}
    use_sonarr = True
    use_radarr = True
    
    [sonarr]
    ip = {{ .Values.sonarr.service.name }}
    port = {{ .Values.sonarr.service.port }}
    base_url = {{ .Values.sonarr.contextPath }}
    ssl = False
    apikey = {{ .Values.sonarr.apiKey }}

    [radarr]
    ip = {{ .Values.radarr.service.name }}
    port = {{ .Values.radarr.service.port }}
    base_url = {{ .Values.radarr.contextPath }}
    ssl = False
    apikey = {{ .Values.radarr.apiKey }}

    [opensubtitles]
    username =
    password =
    use_tag_search = False
    vip = False
    ssl = False
    timeout = 15
    skip_wrong_fps = False

    [opensubtitlescom]
    username =
    password =
    use_hash = True

    [napisy24]
    username =
    password =