apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bazarr
  name: bazarr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
        release: bazarr
    spec:
      containers:
        - image: 'linuxserver/bazarr:latest'
          imagePullPolicy: IfNotPresent
          name: bazarr
          env:
            - name: PUID
              value: {{ quote .Values.PUID }}
            - name: PGID
              value: {{ quote .Values.PGID }}
          # securityContext:
          #   runAsUser: {{ .Values.PUID }}
          #   runAsGroup: {{ .Values.PGID }}
          ports:
            - containerPort: 6767
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config
              name: bazarr-config
            - mountPath: tv
              name: media
              subPath: tv
            - mountPath: movies
              name: media
              subPath: movies
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-server-nfs-pvc
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
