apiVersion: v1
kind: ConfigMap
metadata:
  name: bazarr-configmap
data:
  config.ini: |-
    [general]
    ip = 0.0.0.0
    port = 6767
    base_url = /bazarr
    use_sonarr = True
    use_radarr = True
    
    [sonarr]
    ip = sonarr
    port = 80
    base_url = /sonarr
    ssl = False
    apikey = cf29ec20d9e846b6a819d87472d4c0ae

    [radarr]
    ip = radarr
    port = 80
    base_url = /radarr
    ssl = False
    apikey = fc4232ff8bc648c0a8b34667240b6be5

    [opensubtitles]
    username =
    password =
    use_tag_search = False
    vip = False
    ssl = False
    timeout = 15
    skip_wrong_fps = False

    [opensubtitlescom]
    username =
    password =
    use_hash = True

    [napisy24]
    username =
    password =