apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
spec:
  secretName: grafana-certificate-key-pair
  isCA: true
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: "grafana.raspberrypi"
  emailAddresses:
  - "marcinlagowski92@gmail.com"
  subject:
    organizations:
      - "emlagowski.github.io"
    countries: 
      - "PL"
    provinces: 
      - "Mazowieckie"
    localities: 
      - "Warsaw"
  privateKey:
    algorithm: "ECDSA"
    size: 256
    rotationPolicy: "Always"
  dnsNames:
  - "grafana.raspberrypi"
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "kubernetes.io/metadata.name=istio-system"