apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: "media-ingress"
spec:
  rules:
  - host: media.raspberrypi
    http:
      paths:
        - path: "/transmission"
          pathType: Prefix
          backend:
            service:
              name: "transmission-transmission-openvpn"
              port: 
                name: http
        # - backend:
        #     serviceName: "sonarr"
        #     servicePort: 80
        #   path: "/sonarr"
        - backend:
            serviceName: "jackett"
            servicePort: 80
          path: "/jackett"
        # - backend:
        #     serviceName: "radarr"
        #     servicePort: 80
        #   path: "/radarr"
        # - backend:
        #     serviceName: "plex-kube-plex"
        #     servicePort: 32400
        #   path: "/"