apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: openvpn-credentials
  namespace: media
spec:
  encryptedData:
    credentials.conf: AgCpkcZvDz8ruthQfOdo7WEmDk3ikyCgApjdX8unDliH0EgFfsc75UdOWzKgTC0pADn6FnT+Ni2UqBiIYVUkE6hqErO5snQwC1lJcyaZb4PY73eUwRrUMQYvQy6j5S/XfUbd8o3Soy7mimi5R4ZqtLVswqi34Zxv6Lyr0OBNvIVL7hWnLPy/wrbNJuqVJ9ZwvWrQZTO/8tCECV7ZlCAmtCZhklHZeyoSN98QBCLGzAA0by6E7zZG2LTZNAPkkU2++7vqaXc27u8Gf8PQurHiJBdfOkiOQCt6DNURfA+PEeRnjaTs3UJyx4bcDO1kZ/i88IQ61pciLtQxBzBNfE3S3pwRtMSpyCArXoBGW2/vZTDfAU29UeL9Adks+XqHE7PMoDFXLHPrU7EYZNGs6sYyTcBOP4JiEJpWa03CTE9Uhqqrf32XG2MOFgWDtBNVFgr7TMQ0XG6P5Nm+oSX1CrfPxPkzi7NxoUkc09wyPlgsPeIFrzFAjwuffTC+8xOV2Ymv6ZCR2BnFVRqintuc4UPzNcbUXdJtQ37fzneDbmxqv28RxwjVi+OHDcrqTkhmfZmr98zHTjH2Xc5BMSQ5y4W+0be+C9MreVFBYNCbA/GOPnvOyOe8mpunAXxGlnzUwobU+Y4QJ9sPERXVVg0JPAdsiyxZWhkVtGslZbzru9wgAxaQumqOHzAxl+ephlKACC55klkNtKVTVOJLt3suePrWYiY/JdCmJxd29BL7MrObUu0tar79fBaFzdNqbpMM9L7m/S92
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: openvpn-credentials
      namespace: media

