apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackett
  name: jackett
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      initContainers:
       - name: copy
         image: busybox:1.28
         command: ["/bin/sh", "-c", "cp /config/openvpn/config.ovpn.template /config/openvpn/config.ovpn"]
         volumeMounts:
         - name: openvpn-credentials
           mountPath: /config/openvpn
      containers:
        - env:
            - name: VPN_ENABLED
              value: 'yes'
            - name: VPN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: vpn_username
                  name: media-secrets
            - name: VPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: vpn_password
                  name: media-secrets
            - name: LAN_NETWORK
              value: 192.168.0.0/24
            - name: CREATE_TUN_DEVICE
              value: 'true'
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          image: 'gjeanmart/jackettvpn:latest'
          imagePullPolicy: IfNotPresent
          name: jackett
          ports:
            - containerPort: 9117
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /downloads
              name: media-pvc
              subPath: downloads/jackett
            - mountPath: /config/openvpn
              name: openvpn-credentials
      restartPolicy: Always
      volumes:
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media-pvc
        - name: openvpn-credentials
          secret:
            secretName: openvpn-credentials