apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: media
    server: 'https://kubernetes.default.svc'
  sources:
    - path: ''
      repoURL: 'https://bananaspliff.github.io/geek-charts'
      targetRevision: 0.1.0
      chart: jackett
      helm:
        valueFiles:
          - values.yaml
        values: |
          replicaCount: 1

          image:
            repository: "gjeanmart/jackettvpn" # Special image to use Jackett over a VPN
            tag: "latest"
            pullPolicy: IfNotPresent

          env:
            - name: VPN_ENABLED
              value: "yes" # Enable Jackett over VPN
            - name: VPN_USERNAME
              valueFrom:
                secretKeyRef: # Reference to the secret | openvpn.username
                  name: "media-secrets"
                  key: "vpn_username"
            - name: VPN_PASSWORD
              valueFrom:
                secretKeyRef: # Reference to the secret | openvpn.password
                  name: "media-secrets"
                  key: "vpn_password"
            - name: LAN_NETWORK
              value: "192.168.0.0/24"
            - name: CREATE_TUN_DEVICE
              value: "true" # Needed for VPN
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

          service:
            type: ClusterIP
            port: 80

          volumes:
            - name: "media-pvc"
              persistentVolumeClaim:
                claimName: "media-pvc" # PersistentVolumeClaim created earlier
            - name: openvpn-credentials
              secret:
                secretName: openvpn-credentials

          volumeMounts:
            - name: "media-pvc"
              mountPath: "/downloads"
              subPath: "downloads/jackett" # Path /mnt/ssd/media/downloads/jackett ???
            - mountPath: "/config/openvpn"
              name: openvpn-credentials

          securityContext:
            capabilities: # Needed for VPN
              add:
                - NET_ADMIN

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
