apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: openvpn-credentials
  namespace: media
spec:
  encryptedData:
    credentials.conf: AgA+TQForbxPtleFUgX59vHajEKTAOYM6gpxfbF0fAIjsCNFW5EQ9R1bPUx1Ae8QitnK4/L+qVtUnE3niZNdI3AI3Qi7+WX52Jx7mIkUOV6ZrccoKKJ7jOswszx81fer0KIf0JDE/9JmmkIaM8aDYrJXpxkiL1JzZkf3271diqaMQwwXMe/e9oWL3QQ5u8eS1U7A9tM9OMHPoqlUngYIzABQTsPheoIBRKxv9HoFaSbqwGNfsdhk+f+q0pLgo2/njvs+fqqR+OBieBgtJuApMw3AzgXL+mQsw7XSj24llac65OJDSsCTLJtrNklXSW7g1iiJCYf4AU26XruWuz3INmJIVGJDdVtqkODPjX4AicWxM+rDkbYPZAnrl+Te3O4c/lnKdDzHofgESXeJfdTC7bXa+Rdu+feYUUQ9KFDL21lEe6Rpif6MnbU5y9LNy+TsSNg0EboLrD6lvWN3rLBwnIpa5tp+p6NGd1nIy0FddZBLKCDo95G0pPst4zQSFtSyGDQeVP8cl1eeBt82bvpLmxJL4bkfUW+bvsDvBdMKp9VBQ9+Q3C73wKHBLmny69FlZemqOgmzInTDwH6b8L++wVgkmu3LoC83+GA4zo0pSno2YgFvw6MkkS8xh9sUkQA//79Gw/8QVjiBnSQVJX6zeyLJsLUi5UrkwEEJPv6JAN7xEH71gfI7YCUZ2ObIgb6Eg66otbXnXXx47RsuXumYu+d2L+/Wr6JlTbtU5Nwf0bAEPpey9rQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: openvpn-credentials
      namespace: media

