apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: media
    server: 'https://kubernetes.default.svc'
  sources:
    - path: ''
      repoURL: 'https://ressu.github.io/kube-plex'
      targetRevision: 0.3.5
      chart: kube-plex
      helm:
        valueFiles:
          - values.yaml
        values: |
          claimToken: ""

          image:
            repository: linuxserver/plex
            tag: latest
            pullPolicy: IfNotPresent

          kubePlex:
            enabled: false # kubePlex (transcoder job) is disabled because not available on ARM. The transcoding will be performed by the main Plex instance instead of a separate Job.

          timezone: Europe/Warsaw

          service:
            type: ClusterIP
            port: 32400

          rbac:
            create: true

          nodeSelector: 
            kubernetes.io/arch: arm64 

          persistence:
            data:
              claimName: "media-pvc"
            config:
              size: 10Gi
              accessMode: ReadWriteOnce

          extraEnv:
          - name: PLEX_CLAIM
            valueFrom: 
              secretKeyRef:
                name: "media-secrets"
                key: "plex_claim_token"

          resources: {}
          podAnnotations: {}
          proxy:
            enable: false

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
