apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-8d77c665-c2ea-4d64-9f7c-210e68205103
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/rancher/k3s/storage/pv-media
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem