apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        release: radarr
    spec:
      initContainers:
      - name: copy
        image: busybox:1.28
        env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
        command: ["/bin/sh", "-c"]
        args: 
          - ls /tmp/config/;
            cp /tmp/config/*.xml /config/;
            chown -R ${PUID}:${PGID} /movies;
        volumeMounts:
          - mountPath: /config/
            name: radarr-config
          - mountPath: /tmp/config
            name: radarr-configmap
          - mountPath: /movies
            name: media-pvc
            subPath: library/movies
      containers:
        - image: 'linuxserver/radarr:latest'
          imagePullPolicy: IfNotPresent
          name: radarr
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config
              name: media-pvc
              subPath: configs/radarr
            - mountPath: /downloads/transmission
              name: media-pvc
              subPath: downloads/transmission
            - mountPath: /movies
              name: media-pvc
              subPath: library/movies
            - mountPath: /config/config.xml
              name: radarr-config
              subPath: config.xml
      volumes:
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media-pvc
        - configMap:
            name: radarr-configmap
          name: radarr-configmap
        - name: radarr-config
