apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: media-secrets
  namespace: homebridge
spec:
  encryptedData:
    vpn_password: AgBlut/2g330SxeAEJCOxUyPYv/6mV6HNv5V9TzorkzOJFKF6WriIkSjfWNdb8bLWRaF2H4EK7pgkMYsH/0OQgDiAGllbn7WYUbZllP3iRZtxG8KeZiswt8BEwmExzICJyuc+63pKzze30VcO7S8ZLa0eRDi4+Ljq3r7ZVQaOLG1Y4uToJzMy4b0pqwKfV7aRYAfs06omU+862Q5l4Pcc4/tE1QmEXypZthJA9aRsz4LrhcNeD8ZrnGMH5K8Pu1fOoyngHC+sNXWOexJs7PUiQs3eb+e6FVugdQ/YZ9h9vpLCaS2D1Na4E2vwo/ce3KQgeW8T7HEsLCrA32Np7NL0pimYyqv4cD7IsTaaxGXxfGiXoG2v1FxLpU5bltlFYkf4dr0J4reYus0Qwz3QT0YptqCGU/p1o5eunge5oSiHstdk9XtyGoenM5rSkFg/REvz111YnTlithQi66I9xRDs/MtYIqlUgsjfuLQ4CSfaBPVj6G/EKkUXI2X6iNaWFMdcVN8kAKBWoyOqNMEIEWBNu8YO145PKk5n+CAAH7tLw8TuXa8hHqN2t6tOjcyCzqA/Ex42h+iGEHhAgsq/gHc2qY0yYLBSIbPds5br6ucd8Xsq/06hacH/2p8YlsBmd6VktTs/pHR1+okbMTSvIoO1yOYAMb6O0EqTJ1vkT4t/PwYgKvK1ebRLhqnNRuUO5UNB3LmOOhDfHQTj7RbQaUs++8ud6HYrBVJOug=
    vpn_username: AgBqLi/oVepKhTQVWQMw+oTWtORcr98YVE5JPJEIg2n5tIqic9qnwa5dyxc7SAiueC4Zyp33KBB0udE+9d/JJUWNPcDtLU3I7Esh09Ef3KQ/UALo/cS5To2vRImxAD6pShOQU+QMkMZQCrzdb2aBs0OxZPOCW+onmyTJW+MFcWzkYgJpX7kER8cua3Y036TDvA8Rr82OT3wN3rTVeKh3Nqn/5b665fsYijEApoLmdpcUsm9pyknnyJqrisRHIWuDF4wS/wgPLQ85+22KVRYp2jXJ9SmdW1VGqS3Ay6p7tsw7AfnhUpnrtli6vBME3wJf4KfnqRvp3fTHHZ95m7KUFMpvGv/FuZPIPS50Gux9C7jh+YPXsx93JhMFGoASbez2URD45VqKP7ZlltHm6kHhPuz3KMRNZRV89kN6+MSfgAS838/vHn+QWGLU554ZDTv0ZgEEB5+vf9NMcfEkNaPECSanDK6K+VFQgmFQmLJpdWgeBYgaCR2Gj+PXG9JjElNoduGJFUzKoMt8QRyDCVVXGWwn6rvDaDAqrrnPIGR7hstiFcJqYtJiBrEbo5hM4YkErAelE4ZYYPhll/eNSRU8K2RZn35uUVpTXIp/QcNEef3CNeOrp5ClnzIXLqa2iuTsjnPLa+aUCbMS8ltNOIIile6VY8mZbbju/hX378d7P5a7PCGogHh2h9/EZsxS+UKEEU7jeSHOTltcBcKTVDnwokiVDqpBuxrQn9I=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: media-secrets
      namespace: homebridge

