apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: media
    server: 'https://kubernetes.default.svc'
  sources:
    - path: ''
      repoURL: 'https://bananaspliff.github.io/geek-charts'
      targetRevision: 0.1.0
      chart: sonarr
      helm:
        valueFiles:
          - values.yaml
        values: |
          replicaCount: 1

          image:
            repository: linuxserver/sonarr
            tag: latest # ARM image
            pullPolicy: IfNotPresent

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

          service:
            type: ClusterIP
            port: 80

          volumes:
            - name: "media-pvc"
              persistentVolumeClaim:
                claimName: "media-pvc" # PersistentVolumeClaim created earlier
            - name: sonarr-configmap
              configMap:
                name: sonarr-configmap

          volumeMounts:
            - name: media-pvc
              mountPath: "/config"
              subPath: "configs/sonarr" # Path /mnt/ssd/media/configs/sonarr where sonarr writes the configuration
            - name: media-pvc
              mountPath: "/downloads/transmission"
              subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where sonarr picks up downloaded episodes
            - name: media-pvc
              mountPath: "/tv"
              subPath: "library/tv" # Path /mnt/ssd/media/library/tv where sonarr moves and renames the episodes
            - mountPath: /config/config.xml
              subPath: config.xml
              name: sonarr-configmap
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
