apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "ca-issuer"
    cert-manager.io/common-name: "media.raspberrypi"
  name: "media-ingress"
spec:
  tls:
  - hosts:
    - media.raspberrypi
    secretName: media-auto-certificate-key-pair
  rules:
  - host: media.raspberrypi
    http:
      paths:
        - path: /transmission
          pathType: Prefix
          backend:
            service:
              name: transmission-openvpn
              port: 
                name: http
        - path: /sonarr
          pathType: Prefix
          backend:
            service:
              name: sonarr
              port: 
                name: http
        - path: /radarr
          pathType: Prefix
          backend:
            service:
              name: radarr
              port: 
                name: http
        - path: /prowlarr
          pathType: Prefix
          backend:
            service:
              name: prowlarr
              port: 
                name: http
        - path: /bazarr
          pathType: Prefix
          backend:
            service:
              name: bazarr
              port: 
                name: http