apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "ca-issuer"
    cert-manager.io/common-name: "media.raspberrypi"
  name: "media-ingress"
spec:
  tls:
  - hosts:
    - media.raspberrypi
    secretName: media-auto-certificate-key-pair
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.transmission.contextPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.transmission.service.name }}
              port: 
                name: http
        - path: {{ .Values.sonarr.contextPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.sonarr.service.name }}
              port: 
                name: http
        - path: {{ .Values.radarr.contextPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.radarr.service.name }}
              port: 
                name: http
        - path: {{ .Values.prowlarr.contextPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.prowlarr.service.name }}
              port: 
                name: http
        - path: {{ .Values.bazarr.contextPath }}
          pathType: Prefix
          backend:
            service:
              name: "bazarr"
              port: 
                name: http
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: "plex"
              port: 
                name: pms