apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: "overseerr-ingress"
spec:
  tls:
  - hosts:
    - overseerr.raspberrypi
    secretName: overseerr-certificate-key-pair
  rules:
  - host: {{ .Values.overseerr.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.overseerr.service.name }}
            port:
              name: http