apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/rancher/k3s/storage/pv-media
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem