apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: media-pv
  resources:
    requests:
      storage: 10Gi