apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolume.claimName }}
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  # volumeMode: Filesystem
  # volumeName: {{ .Values.persistentVolume.name }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}