apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission-openvpn
  name: {{ .Values.transmission.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.transmission.service.port }}
      protocol: TCP
      targetPort: 9091
  selector:
    app: transmission-openvpn
  type: ClusterIP
