apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission-openvpn
  name: transmission-openvpn
spec:
  replicas: {{ .Values.transmission.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: transmission-openvpn
  template:
    metadata:
      labels:
        app: transmission-openvpn
    spec:
      containers:
        - image: 'haugene/transmission-openvpn:latest'
          imagePullPolicy: IfNotPresent
          name: transmission-openvpn
          env:
            - name: OPENVPN_PROVIDER
              value: NORDVPN
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.vpn.secret.usernameKey }}
                  name: {{ .Values.vpn.secret.name }}
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.vpn.secret.passwordKey }}
                  name: {{ .Values.vpn.secret.name }}
            - name: NORDVPN_PROTOCOL
              value: TCP
            - name: NORDVPN_COUNTRY
              value: {{ .Values.vpn.country }}
            - name: NORDVPN_CATEGORY
              value: P2P
            - name: LOCAL_NETWORK
              value: 192.168.0.0/24
            - name: TRANSMISSION_PEER_PORT
              value: '47444'
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: "/{{ .Values.transmission.dataPath }}"
            - name: PUID
              value: {{ quote .Values.PUID }}
            - name: PGID
              value: {{ quote .Values.PGID }}
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: configs/transmission-data
            - mountPath: /downloads/transmission
              name: data
              subPath: "{{ .Values.transmission.dataPath }}"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      dnsPolicy: None
      restartPolicy: Always
      schedulerName: default-scheduler
      nodeSelector:
        storage: "true"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
