apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-incomplete-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Gi