apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: "cert-manager"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: marcinlagowski92@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.mlagowski.com
          solverName: ovh
          config:
            endpoint: ovh-eu
            applicationKey: 6c08126c34ffa8d1
            applicationSecretRef:
              key: applicationSecret
              name: ovh-credentials
            consumerKey: e4145753dd826d605890c0f1a06e7aa9