apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "ca-issuer"
    cert-manager.io/common-name: "argocd.lab.mlagowski.com"
  name: argocd-ingress
spec:
  tls:
  - hosts:
    - argocd.lab.mlagowski.com
    secretName: argocd-auto-certificate-key-pair
  rules:
  - host: argocd.lab.mlagowski.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
