apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      hostNetwork: true
      containers:
        - image: klutchell/unbound:main
          name: unbound
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 300m
          ports:
            - containerPort: 53
          volumeMounts:
            - name: unbound-config
              mountPath: /etc/unbound/custom.conf.d/raspberrypi.conf
              subPath: raspberrypi.conf
            - name: unbound-config
              mountPath: /etc/unbound/custom.conf.d/homebridge.conf
              subPath: homebridge.conf
      volumes:
        - name: unbound-config
          configMap:
            name: custom-configmap