apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-configmap
  namespace: homebridge
data:
  config.json: |
    {
        "bridge": {
            "pin": "719-11-047",
            "username": "0E:CC:AD:BD:D6:A4",
            "name": "Homebridge D6A4",
            "port": 51132
        },
        "platforms": [
            {
                "platform": "config",
                "port": 8090,
                "name": "Config"
            }
        ],
        "accessories": [
           
        ]
    }
  auth.json: |
    [
      {
          "id": 1,
          "username": "marcinlagowski",
          "name": "marcinlagowski",
          "hashedPassword": "a77fdfcacb94d36d59c1eb421cbbb6cd42727fbb26aa4601d393f84a5313e8a4754a41bf4dfc56afad4039bb76d05a7d0d2a610f3194a0a83b2f1e1a2f814345",
          "salt": "eedb063faf1e20802c806a30bf6923885766a8f43c79e51586314d8d585cc20b",
          "admin": true
      }
    ]
  startup.sh: |
    #!/bin/bash
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-midea-air 1.7.3 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-xiaomi-roborock-vacuum 0.29.0 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-samsung-tizen 5.2.6 /var/lib/homebridge/node_modules