apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-configmap
  namespace: homebridge
data:
  config.json: |
    {
        "bridge": {
            "name": "Homebridge E7C8",
            "username": "$HOMEBRIDGE_USERNAME",
            "port": 51221,
            "pin": "$HOMEBRIDGE_PIN",
            "advertiser": "bonjour-hap"
        },
        "platforms": [
            {
                "platform": "config",
                "port": 8090,
                "name": "Config"
            },
            {
                "interval": 30,
                "platform": "midea-air",
                "password": "$HOMEBRIDGE_MIDEA_PASSWORD",
                "user": "$HOMEBRIDGE_MIDEA_USER",
                "devices": [
                    {
                        "OutdoorTemperature": true,
                        "supportedSwingMode": "Both",
                        "deviceId": "$HOMEBRIDGE_MIDEA_DEVICE_ID",
                        "fanOnlyMode": true
                    }
                ]
            },
            {
                "app_list": true,
                "devices": [
                    {
                        "name": "Samsung TV 65",
                        "ip": "192.168.1.141",
                        "mac": "$HOMEBRIDGE_TV_MAC",
                        "inputs": [
                            {
                                "type": "app",
                                "name": "Netflix",
                                "value": "11101200001"
                            },
                            {
                                "type": "app",
                                "name": "YouTube",
                                "value": "111299001912"
                            },
                            {
                                "type": "app",
                                "name": "Spotify",
                                "value": "3201606009684"
                            }
                        ]
                    }
                ],
                "platform": "SamsungTizen"
            },
            {
                "zones": [
                    {
                        "name": "Salon TV Audio",
                        "priorities": [
                            "Gabinet 2x1",
                            "Sypialnia Five",
                            "Łazienka Sypialnia",
                            "Kuchnia"
                        ]
                    },
                    {
                        "name": "Sypialnia Five",
                        "priorities": [
                            "Salon TV Audio",
                            "Gabinet 2x1",
                            "Łazienka Sypialnia",
                            "Kuchnia"
                        ]
                    },
                    {
                        "name": "Gabinet 2x1",
                        "priorities": [
                            "Salon TV Audio",
                            "Sypialnia Five",
                            "Łazienka Sypialnia",
                            "Kuchnia"
                        ]
                    },
                    {
                        "name": "Kuchnia",
                        "priorities": [
                            "Salon TV Audio",
                            "Gabinet 2x1",
                            "Sypialnia Five",
                            "Łazienka Sypialnia"
                        ]
                    },
                    {
                        "name": "Łazienka Sypialnia",
                        "priorities": [
                            "Salon TV Audio",
                            "Gabinet 2x1",
                            "Sypialnia Five",
                            "Kuchnia"
                        ]
                    }
                ],
                "isApiEnabled": false,
                "platform": "SonosMultiroomPlatform"
            }
        ],
        "accessories": [
            {
                "name": "Roborock S5",
                "ip": "192.168.1.205",
                "token": "$HOMEBRIDGE_XIAOMI_TOKEN",
                "waterBox": false,
                "silent": false,
                "pause": true,
                "pauseWord": "pause",
                "findMe": true,
                "findMeWord": "where are you",
                "dock": true,
                "cleanword": "cleaning",
                "roomTimeout": 0,
                "autoroom": false,
                "accessory": "XiaomiRoborockVacuum"
            }
        ]
    }
  auth.json: |
    [
      {
          "id": 1,
          "username": "$HOMEBRIDGE_ADMIN_USER",
          "name": "$HOMEBRIDGE_ADMIN_USER",
          "hashedPassword": "$HOMEBRIDGE_ADMIN_PASSWORD",
          "salt": "$HOMEBRIDGE_ADMIN_SALT",
          "admin": true
      }
    ]
  startup.sh: |
    #!/bin/bash

    # install plugins
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-midea-air 1.7.3 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-xiaomi-roborock-vacuum 0.34.0 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-samsung-tizen 5.3.3 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-sonos-multiroom 0.6.0 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-appletv-enhanced 0.1211 /var/lib/homebridge/node_modules
    /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-zp 1.4.54 /var/lib/homebridge/node_modules

    # install envsubst
    apt-get update
    apt-get install gettext-base

    # pass secrets to config files from env variables
    envsubst < /homebridge/config.json.template > /homebridge/config.json
    envsubst < /homebridge/auth.json.template > /homebridge/auth.json