kind: Deployment
apiVersion: apps/v1
metadata:
  name: homebridge
  labels:
    app: homebridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      volumes:
      - name: homebridge
        persistentVolumeClaim:
          claimName: homebridge-pv-claim
      - name: homebridge-config
        configMap:
          name: homebridge-configmap
          defaultMode: 0711
      hostNetwork: true
      containers:
        - name: homebridge
          volumeMounts:
          #   - mountPath: "/homebridge"
          #     name: homebridge
            - name: homebridge-config
              mountPath: /homebridge/config.json
              subPath: config.json
            - name: homebridge-config
              mountPath: /homebridge/auth.json
              subPath: auth.json
            - name: homebridge-config
              mountPath: /homebridge/startup.sh
              subPath: startup.sh
          image: oznu/homebridge:2023-01-08
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            allowPrivilegeEscalation: true
          env:
            - name: TERMINATE_ON_ERROR
              value: "1"
            - name: HOMEBRIDGE_CONFIG_UI
              value: "1"
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "8090"
            - name: PUID
              value: "1000"
            - name: PUID
              value: "1000"
            # - name: PACKAGES
            #   value: "1"
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8090
          readinessProbe:
            httpGet:
              path: /
              port: 8090
          startupProbe:
            httpGet:
              path: /
              port: 8090
            failureThreshold: 30
            periodSeconds: 10