apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pv-claim
spec:
  storageClassName: homebridge-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi