apiVersion: v1
kind: Service
metadata:
  name: homebridge
spec:
  selector:
    app: homebridge
  ports:
    - name: ui
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: homebridge
      port: 51132
      targetPort: 51132
      protocol: TCP