apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kiali-operator
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://kiali.org/helm-charts'
      targetRevision: 1.73.0
      chart: kiali-operator
      helm:
        values: |
          cr:
            create: true
            namespace: istio-system
            spec:
              deployment:
                ingress:
                  enabled: false
              external_services:
                prometheus:
                  custom_metrics_url: http://monitoring-prometheus.monitoring.svc.cluster.local:9090/
                  url: http://monitoring-prometheus.monitoring.svc.cluster.local:9090/
                  component_status:
                    app_label: "prometheus"
                    is_core: true
                    namespace: "monitoring"
    # - path: kiali
    #   repoURL: 'https://github.com/emlagowski/home-apps.git'
    #   targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true