apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://charts.appscode.com/stable/'
      targetRevision: 0.12.0
      chart: 'kubed'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true