apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  sources:
    - path: monitoring
      repoURL: 'https://github.com/emlagowski/home-apps.git'
      targetRevision: HEAD
    - path: ''
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 48.3.2
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - values.yaml
        values: |
          nameOverride: monitoring
          namespaceOverride: monitoring
          kubeTargetVersionOverride: 1.22.3
          grafana:
            ingress:
              enabled: true
              hosts:
              - grafana.raspberrypi
              annotations:
                kubernetes.io/ingress.class: "istio"
              tls:
              - hosts:
                - grafana.raspberrypi
                secretName: grafana-certificate-key-pair
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # https://blog.ediri.io/kube-prometheus-stack-and-argocd-25-server-side-apply-to-the-rescue
      - ServerSideApply=true
      - CreateNamespace=true
