apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nfs-provisioner
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner'
      targetRevision: 4.0.18
      chart: 'nfs-subdir-external-provisioner'
      helm:
        storageClass.name: nfs
        values: |
          nfs:
            server: 192.168.1.156
            path: "/volume1/Media Server"
            mountOptions:
            - nfsvers=4.1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true