apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pi-hole
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
    targetRevision: 2.18.0
    chart: pihole
    helm:
      valueFiles:
        - values.yaml
      values: |
        virtualHost: pi-hole.raspberrypi

        hostNetwork: true

        webHttp: "8080"
        webHttps: "8443"

        # dnsHostPort:
        #   enabled: true

        customDnsEntries: 
        - address=/raspberrypi/192.168.1.39
        - address=/argocd.raspberrypi/192.168.1.39

        ingress:
          enabled: true
          hosts:
          - pi-hole.raspberrypi

        persistentVolumeClaim:
          enabled: true

        podDnsConfig:
          enabled: true
          policy: "None"
          nameservers:
          - 127.0.0.1
          - 1.1.1.1
          - 8.8.8.8

        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        extraEnvVars: {
          DNSMASQ_USER: "root"
        }
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
