apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pi-hole
    server: 'https://kubernetes.default.svc'
  sources:
    - path: pi-hole
      repoURL: 'https://github.com/emlagowski/home-apps.git'
      targetRevision: HEAD
    - path: ''
      repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
      targetRevision: 2.18.0
      chart: pihole
      helm:
        valueFiles:
          - values.yaml
        values: |
          virtualHost: pi-hole.raspberrypi

          hostNetwork: true

          webHttp: "8080"
          webHttps: "8443"

          admin:
            existingSecret: "pi-hole-pihole-custom-password"
            passwordKey: "password"

          dnsmasq:
            customDnsEntries: 
            - address=/raspberrypi/192.168.1.39

          ingress:
            enabled: true
            hosts:
            - pi-hole.raspberrypi

          DNS1: "1.1.1.1"
          DNS2: "8.8.8.8"

          persistentVolumeClaim:
            enabled: true

          podDnsConfig:
            enabled: false

          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

          nodeSelector:
            node-role.kubernetes.io/master: "true"

          extraEnvVars: {
            DNSMASQ_USER: "root"
          }
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
