apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonos-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sonos-api
    server: 'https://kubernetes.default.svc'
  sources:
    - path: sonos
      repoURL: 'https://github.com/emlagowski/home-apps.git'
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true