apiVersion: v1
kind: Service
metadata:
  labels:
    app: prowlarr
  name: {{ .Values.prowlarr.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.prowlarr.service.port }}
      protocol: TCP
      targetPort: 9696
  selector:
    app: prowlarr
  type: ClusterIP
