apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
  name: prowlarr
spec:
  replicas: {{ .Values.prowlarr.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
        release: prowlarr
    spec:
      containers:
        - image: 'linuxserver/prowlarr:latest'
          imagePullPolicy: IfNotPresent
          name: prowlarr
          env:
            - name: PUID
              value: {{ quote .Values.PUID }}
            - name: PGID
              value: {{ quote .Values.PGID }}
          ports:
            - containerPort: 9696
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: {{ .Values.prowlarr.configPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
