apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca-certificate
spec:
  secretName: selfsigned-ca-key-pair
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "raspberrypi"
  emailAddresses:
  - "marcinlagowski92@gmail.com"
  subject:
    organizations:
      - "emlagowski.github.io"
    countries: 
      - "PL"
    provinces: 
      - "Mazowieckie"
    localities: 
      - "Warsaw"
  privateKey:
    algorithm: "ECDSA"
    size: 256
    rotationPolicy: "Always"
  dnsNames:
  - raspberrypi
  secretTemplate:
    annotations:
      emlagowski.github.io/test: "true"