apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett-configmap
data:
  ServerConfig.json: |-
    {
      "BasePathOverride": "{{ .Values.jackett.contextPath }}",
      "APIKey": "{{ .Values.jackett.apiKey }}"
    }
{{ (.Files.Glob "files/*.ovpn").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett-indexers-configmap
data:
{{ (.Files.Glob "files/indexers/*.json").AsConfig | indent 2 }}