apiVersion: v1
kind: Service
metadata:
  labels:
    app: jackett
  name: {{ .Values.jackett.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.jackett.service.port }}
      protocol: TCP
      targetPort: 9117
  selector:
    app: jackett
  type: ClusterIP
