apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett-configmap
data:
  ServerConfig.json: |-
    {
      "BasePathOverride": "{{ .Values.jackett.contextPath }}"
    }
{{ (.Files.Glob "files/*.ovpn").AsConfig | indent 2 }}